//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KursovayaRabotaKalyukh
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вид носителя.
    /// </summary>
    // *** Start programmer edit section *** (ВидНосителя CustomAttributes)

    // *** End programmer edit section *** (ВидНосителя CustomAttributes)
    public enum ВидНосителя
    {
        
        // *** Start programmer edit section *** (ВидНосителя.Флешка CustomAttributes)

        // *** End programmer edit section *** (ВидНосителя.Флешка CustomAttributes)
        [Caption("Флешка")]
        Флешка,
        
        // *** Start programmer edit section *** (ВидНосителя.ФлешКарта CustomAttributes)

        // *** End programmer edit section *** (ВидНосителя.ФлешКарта CustomAttributes)
        [Caption("Флеш карта")]
        ФлешКарта,
    }
}
