//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KursovayaRabotaKalyukh
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиент.
    /// </summary>
    // *** Start programmer edit section *** (Клиент CustomAttributes)

    // *** End programmer edit section *** (Клиент CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлиентE", new string[] {
            "ID as \'ID\'"})]
    [View("КлиентL", new string[] {
            "ID as \'ID\'"})]
    public class Клиент : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        // *** Start programmer edit section *** (Клиент CustomMembers)

        // *** End programmer edit section *** (Клиент CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Клиент.ID CustomAttributes)

        // *** End programmer edit section *** (Клиент.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Клиент.ID Get start)

                // *** End programmer edit section *** (Клиент.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Клиент.ID Get end)

                // *** End programmer edit section *** (Клиент.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиент.ID Set start)

                // *** End programmer edit section *** (Клиент.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Клиент.ID Set end)

                // *** End programmer edit section *** (Клиент.ID Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлиентE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентE", typeof(IIS.KursovayaRabotaKalyukh.Клиент));
                }
            }
            
            /// <summary>
            /// "КлиентL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентL", typeof(IIS.KursovayaRabotaKalyukh.Клиент));
                }
            }
        }
    }
}
