//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KursovayaRabotaKalyukh
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Проверка киоска.
    /// </summary>
    // *** Start programmer edit section *** (ПроверкаКиоска CustomAttributes)

    // *** End programmer edit section *** (ПроверкаКиоска CustomAttributes)
    [AutoAltered()]
    [Caption("Проверка киоска")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПроверкаКиоскаE", new string[] {
            "Фотокиоск as \'Фотокиоск\'",
            "Фотокиоск.Наименование as \'Наименование\'",
            "Оператор as \'Оператора\'",
            "Оператор.ФИО as \'ФИО\'",
            "Оператор.КодВхода as \'Пароль\'",
            "КартЗаправ as \'Картридж заправлен\'",
            "Бумага as \'Бумага\'",
            "ДатаПроверки as \'Дата проверки\'",
            "ВремяПроверки as \'Время проверки\'",
            "ГотовКРаботе as \'Готов к работе\'"})]
    [View("ПроверкаКиоскаL", new string[] {
            "Фотокиоск.Наименование as \'Фотокиоск\'",
            "Оператор.ФИО as \'ФИО\'",
            "Оператор.КодВхода as \'Пароль\'",
            "КартЗаправ as \'Картридж заправлен\'",
            "Бумага as \'Бумага\'",
            "ДатаПроверки as \'Дата проверки\'",
            "ВремяПроверки as \'Время проверки\'",
            "ГотовКРаботе as \'Готов к работе\'"})]
    public class ПроверкаКиоска : ICSSoft.STORMNET.DataObject
    {
        
        private bool fКартЗаправ;
        
        private bool fБумага;
        
        private System.DateTime fДатаПроверки;
        
        private string fВремяПроверки;
        
        private bool fГотовКРаботе;
        
        private IIS.KursovayaRabotaKalyukh.Оператор fОператор;
        
        private IIS.KursovayaRabotaKalyukh.Фотокиоск fФотокиоск;
        
        // *** Start programmer edit section *** (ПроверкаКиоска CustomMembers)

        // *** End programmer edit section *** (ПроверкаКиоска CustomMembers)

        
        /// <summary>
        /// Бумага.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаКиоска.Бумага CustomAttributes)

        // *** End programmer edit section *** (ПроверкаКиоска.Бумага CustomAttributes)
        public virtual bool Бумага
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаКиоска.Бумага Get start)

                // *** End programmer edit section *** (ПроверкаКиоска.Бумага Get start)
                bool result = this.fБумага;
                // *** Start programmer edit section *** (ПроверкаКиоска.Бумага Get end)

                // *** End programmer edit section *** (ПроверкаКиоска.Бумага Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаКиоска.Бумага Set start)

                // *** End programmer edit section *** (ПроверкаКиоска.Бумага Set start)
                this.fБумага = value;
                // *** Start programmer edit section *** (ПроверкаКиоска.Бумага Set end)

                // *** End programmer edit section *** (ПроверкаКиоска.Бумага Set end)
            }
        }
        
        /// <summary>
        /// ВремяПроверки.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаКиоска.ВремяПроверки CustomAttributes)

        // *** End programmer edit section *** (ПроверкаКиоска.ВремяПроверки CustomAttributes)
        [StrLen(255)]
        public virtual string ВремяПроверки
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаКиоска.ВремяПроверки Get start)

                // *** End programmer edit section *** (ПроверкаКиоска.ВремяПроверки Get start)
                string result = this.fВремяПроверки;
                // *** Start programmer edit section *** (ПроверкаКиоска.ВремяПроверки Get end)

                // *** End programmer edit section *** (ПроверкаКиоска.ВремяПроверки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаКиоска.ВремяПроверки Set start)

                // *** End programmer edit section *** (ПроверкаКиоска.ВремяПроверки Set start)
                this.fВремяПроверки = value;
                // *** Start programmer edit section *** (ПроверкаКиоска.ВремяПроверки Set end)

                // *** End programmer edit section *** (ПроверкаКиоска.ВремяПроверки Set end)
            }
        }
        
        /// <summary>
        /// ГотовКРаботе.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаКиоска.ГотовКРаботе CustomAttributes)

        // *** End programmer edit section *** (ПроверкаКиоска.ГотовКРаботе CustomAttributes)
        public virtual bool ГотовКРаботе
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаКиоска.ГотовКРаботе Get start)

                // *** End programmer edit section *** (ПроверкаКиоска.ГотовКРаботе Get start)
                bool result = this.fГотовКРаботе;
                // *** Start programmer edit section *** (ПроверкаКиоска.ГотовКРаботе Get end)

                // *** End programmer edit section *** (ПроверкаКиоска.ГотовКРаботе Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаКиоска.ГотовКРаботе Set start)

                // *** End programmer edit section *** (ПроверкаКиоска.ГотовКРаботе Set start)
                this.fГотовКРаботе = value;
                // *** Start programmer edit section *** (ПроверкаКиоска.ГотовКРаботе Set end)

                // *** End programmer edit section *** (ПроверкаКиоска.ГотовКРаботе Set end)
            }
        }
        
        /// <summary>
        /// ДатаПроверки.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаКиоска.ДатаПроверки CustomAttributes)

        // *** End programmer edit section *** (ПроверкаКиоска.ДатаПроверки CustomAttributes)
        public virtual System.DateTime ДатаПроверки
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаКиоска.ДатаПроверки Get start)

                // *** End programmer edit section *** (ПроверкаКиоска.ДатаПроверки Get start)
                System.DateTime result = this.fДатаПроверки;
                // *** Start programmer edit section *** (ПроверкаКиоска.ДатаПроверки Get end)

                // *** End programmer edit section *** (ПроверкаКиоска.ДатаПроверки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаКиоска.ДатаПроверки Set start)

                // *** End programmer edit section *** (ПроверкаКиоска.ДатаПроверки Set start)
                this.fДатаПроверки = value;
                // *** Start programmer edit section *** (ПроверкаКиоска.ДатаПроверки Set end)

                // *** End programmer edit section *** (ПроверкаКиоска.ДатаПроверки Set end)
            }
        }
        
        /// <summary>
        /// КартЗаправ.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаКиоска.КартЗаправ CustomAttributes)

        // *** End programmer edit section *** (ПроверкаКиоска.КартЗаправ CustomAttributes)
        public virtual bool КартЗаправ
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаКиоска.КартЗаправ Get start)

                // *** End programmer edit section *** (ПроверкаКиоска.КартЗаправ Get start)
                bool result = this.fКартЗаправ;
                // *** Start programmer edit section *** (ПроверкаКиоска.КартЗаправ Get end)

                // *** End programmer edit section *** (ПроверкаКиоска.КартЗаправ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаКиоска.КартЗаправ Set start)

                // *** End programmer edit section *** (ПроверкаКиоска.КартЗаправ Set start)
                this.fКартЗаправ = value;
                // *** Start programmer edit section *** (ПроверкаКиоска.КартЗаправ Set end)

                // *** End programmer edit section *** (ПроверкаКиоска.КартЗаправ Set end)
            }
        }
        
        /// <summary>
        /// Проверка киоска.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаКиоска.Оператор CustomAttributes)

        // *** End programmer edit section *** (ПроверкаКиоска.Оператор CustomAttributes)
        [PropertyStorage(new string[] {
                "Оператор"})]
        [NotNull()]
        public virtual IIS.KursovayaRabotaKalyukh.Оператор Оператор
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаКиоска.Оператор Get start)

                // *** End programmer edit section *** (ПроверкаКиоска.Оператор Get start)
                IIS.KursovayaRabotaKalyukh.Оператор result = this.fОператор;
                // *** Start programmer edit section *** (ПроверкаКиоска.Оператор Get end)

                // *** End programmer edit section *** (ПроверкаКиоска.Оператор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаКиоска.Оператор Set start)

                // *** End programmer edit section *** (ПроверкаКиоска.Оператор Set start)
                this.fОператор = value;
                // *** Start programmer edit section *** (ПроверкаКиоска.Оператор Set end)

                // *** End programmer edit section *** (ПроверкаКиоска.Оператор Set end)
            }
        }
        
        /// <summary>
        /// Проверка киоска.
        /// </summary>
        // *** Start programmer edit section *** (ПроверкаКиоска.Фотокиоск CustomAttributes)

        // *** End programmer edit section *** (ПроверкаКиоска.Фотокиоск CustomAttributes)
        [PropertyStorage(new string[] {
                "Фотокиоск"})]
        [NotNull()]
        public virtual IIS.KursovayaRabotaKalyukh.Фотокиоск Фотокиоск
        {
            get
            {
                // *** Start programmer edit section *** (ПроверкаКиоска.Фотокиоск Get start)

                // *** End programmer edit section *** (ПроверкаКиоска.Фотокиоск Get start)
                IIS.KursovayaRabotaKalyukh.Фотокиоск result = this.fФотокиоск;
                // *** Start programmer edit section *** (ПроверкаКиоска.Фотокиоск Get end)

                // *** End programmer edit section *** (ПроверкаКиоска.Фотокиоск Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроверкаКиоска.Фотокиоск Set start)

                // *** End programmer edit section *** (ПроверкаКиоска.Фотокиоск Set start)
                this.fФотокиоск = value;
                // *** Start programmer edit section *** (ПроверкаКиоска.Фотокиоск Set end)

                // *** End programmer edit section *** (ПроверкаКиоска.Фотокиоск Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПроверкаКиоскаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПроверкаКиоскаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПроверкаКиоскаE", typeof(IIS.KursovayaRabotaKalyukh.ПроверкаКиоска));
                }
            }
            
            /// <summary>
            /// "ПроверкаКиоскаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПроверкаКиоскаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПроверкаКиоскаL", typeof(IIS.KursovayaRabotaKalyukh.ПроверкаКиоска));
                }
            }
        }
    }
}
