//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KursovayaRabotaKalyukh
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Товары.
    /// </summary>
    // *** Start programmer edit section *** (Товары CustomAttributes)

    // *** End programmer edit section *** (Товары CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТоварыE", new string[] {
            "Код as \'Код\'",
            "Вид as \'Вид фото\'",
            "Стоимость as \'Стоимость\'"})]
    [View("ТоварыL", new string[] {
            "Код as \'Код\'",
            "Вид as \'Вид\'",
            "Стоимость as \'Стоимость\'"})]
    public class Товары : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private string fВид;
        
        private int fСтоимость;
        
        // *** Start programmer edit section *** (Товары CustomMembers)

        // *** End programmer edit section *** (Товары CustomMembers)

        
        /// <summary>
        /// Вид.
        /// </summary>
        // *** Start programmer edit section *** (Товары.Вид CustomAttributes)

        // *** End programmer edit section *** (Товары.Вид CustomAttributes)
        [StrLen(255)]
        public virtual string Вид
        {
            get
            {
                // *** Start programmer edit section *** (Товары.Вид Get start)

                // *** End programmer edit section *** (Товары.Вид Get start)
                string result = this.fВид;
                // *** Start programmer edit section *** (Товары.Вид Get end)

                // *** End programmer edit section *** (Товары.Вид Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товары.Вид Set start)

                // *** End programmer edit section *** (Товары.Вид Set start)
                this.fВид = value;
                // *** Start programmer edit section *** (Товары.Вид Set end)

                // *** End programmer edit section *** (Товары.Вид Set end)
            }
        }
        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (Товары.Код CustomAttributes)

        // *** End programmer edit section *** (Товары.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (Товары.Код Get start)

                // *** End programmer edit section *** (Товары.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (Товары.Код Get end)

                // *** End programmer edit section *** (Товары.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товары.Код Set start)

                // *** End programmer edit section *** (Товары.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (Товары.Код Set end)

                // *** End programmer edit section *** (Товары.Код Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (Товары.Стоимость CustomAttributes)

        // *** End programmer edit section *** (Товары.Стоимость CustomAttributes)
        public virtual int Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (Товары.Стоимость Get start)

                // *** End programmer edit section *** (Товары.Стоимость Get start)
                int result = this.fСтоимость;
                // *** Start programmer edit section *** (Товары.Стоимость Get end)

                // *** End programmer edit section *** (Товары.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товары.Стоимость Set start)

                // *** End programmer edit section *** (Товары.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (Товары.Стоимость Set end)

                // *** End programmer edit section *** (Товары.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТоварыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварыE", typeof(IIS.KursovayaRabotaKalyukh.Товары));
                }
            }
            
            /// <summary>
            /// "ТоварыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварыL", typeof(IIS.KursovayaRabotaKalyukh.Товары));
                }
            }
        }
    }
}
