//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KursovayaRabotaKalyukh
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Фотокиоск.
    /// </summary>
    // *** Start programmer edit section *** (Фотокиоск CustomAttributes)

    // *** End programmer edit section *** (Фотокиоск CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ФотокиоскE", new string[] {
            "Наименование as \'Наименование\'",
            "Адрес as \'Адрес\'"})]
    [View("ФотокиоскL", new string[] {
            "Наименование as \'Наименование\'",
            "Адрес as \'Адрес\'"})]
    public class Фотокиоск : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private string fАдрес;
        
        // *** Start programmer edit section *** (Фотокиоск CustomMembers)

        // *** End programmer edit section *** (Фотокиоск CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Фотокиоск.Адрес CustomAttributes)

        // *** End programmer edit section *** (Фотокиоск.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Фотокиоск.Адрес Get start)

                // *** End programmer edit section *** (Фотокиоск.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Фотокиоск.Адрес Get end)

                // *** End programmer edit section *** (Фотокиоск.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Фотокиоск.Адрес Set start)

                // *** End programmer edit section *** (Фотокиоск.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Фотокиоск.Адрес Set end)

                // *** End programmer edit section *** (Фотокиоск.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Фотокиоск.Наименование CustomAttributes)

        // *** End programmer edit section *** (Фотокиоск.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Фотокиоск.Наименование Get start)

                // *** End programmer edit section *** (Фотокиоск.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Фотокиоск.Наименование Get end)

                // *** End programmer edit section *** (Фотокиоск.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Фотокиоск.Наименование Set start)

                // *** End programmer edit section *** (Фотокиоск.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Фотокиоск.Наименование Set end)

                // *** End programmer edit section *** (Фотокиоск.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ФотокиоскE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФотокиоскE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФотокиоскE", typeof(IIS.KursovayaRabotaKalyukh.Фотокиоск));
                }
            }
            
            /// <summary>
            /// "ФотокиоскL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФотокиоскL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФотокиоскL", typeof(IIS.KursovayaRabotaKalyukh.Фотокиоск));
                }
            }
        }
    }
}
